version: "3.3"

services:
  postgres:
    image: postgres:latest
    volumes:
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"

#volumes:
#  postgres-data:
